### ISSUE TITLE
No Inflow and Outflow and columns

### ISSUE THREAD

**Issue by beblawi** [aniav/ynab-csv#1]
The output file seems to have an 'Amount' column. YNAB format now requires a separate column for Inflow and Outflow.  

Sample Formatting - Text Editor
The first line is the header, the second line is an example outflow, and the last line is an example inflow.
Date,Payee,Memo,Outflow,Inflow
07/23/16,Payee 1,Memo,100.00,
07/24/16,Payee 2,Memo,,500.00

https://docs.youneedabudget.com/article/921-importing-a-csv-file

**Comment by aniav** [comment]
@beblawi so does the resulting file not work for you? I know docs state there should be two columns, but I use the tool on a regular basis and it works just fine with one column, in fact I am wondering if the docs are up to date about the columns.

**Comment by marcorivm** [comment]
Adding on this, what would also be nice is having the ability to choose inflow and outflow columns from input file

**Comment by jdambacher** [comment]
@marcorivm @aniav My bank is using one column for the amount with a '-' sign if it's an outflow. Maybe we could implement that in the output generator (all negative amounts => outflow, all positive amounts => inflow). I'll take a look at the code and maybe find a solution and create a PR.

**Comment by aniav** [comment]
Added that! Can you check if it works ok? I would appreciate anonymised CSVs for tests whenever you have time. I would fill them in test cases. Any help much appreciated :)

**Comment by jdambacher** [comment]
Attached you will find a basic CSV (anonymised) from my bank (Consorsbank). Unfortunately, it's in German, but probably you can work with it.
[Umsatzübersicht_220454625.txt](https://github.com/aniav/ynab-csv/files/1772262/Umsatzubersicht_220454625.txt)

Note: had to upload this file as .txt because of GitHub's restrictions.

**Comment by aniav** [comment]
Awesome, thank you! 🌟

**Comment by jdambacher** [comment]
Any news about that? Did my csv helped you?

**Comment by aniav** [comment]
@jdambacher did you ckeck if the current version works for you? Are there any issues with it? TBH I don't remember if I used your file but I made the required changes.

**Comment by jdambacher** [comment]
@aniav I've tried it yesterday, but it seems it's not working. It's only working if I adjust the input file and split all negative values to a new outflow column and all positive values to a new inflow column.

**Comment by aniav** [comment]
@jdambacher I will check then. That's strange, my bank also has just one column for that and it's being split properly. Thank you for the report! 👍

**Comment by aniav** [comment]
@jdambacher I used the file you provided and it now works properly with -/+ signs. I'll close that for now, but feel free to reopen and comment if there is still something wrong ☕️
