### ISSUE TITLE
Output filename "Unknown" in Safari

### ISSUE THREAD

**Issue by ErikLitonius** [aniav/ynab-csv#11]
The saved file is named "Unknown", with no extension. Would it be possible to at least add a .csv extension? Now the user has to rename the file manually before importing into YNAB. I'm using the converter on MacOS Mojave and Safari.

**Comment by aniav** [comment]
Hey @ErikLitonius the file shouldn't ever be called Unknown if everything worked properly. Can you give me a bit more details? Do you maybe get any console errors? If the file is called `Unknown` I would expect something failed there with date related stuff/locale, it should be called `ynab_data_yyyymmdd`, generated in [this line](https://github.com/aniav/ynab-csv/blob/gh-pages/src/app.js#L143). I would be happy to assist you if you provide some more context 🙏

**Comment by aniav** [comment]
Oh I actually noticed just now that you said this behaviour is happening on Safari, which is actually a known bug, which I didn't try to tackle with. I'll see if I can do anything with it 🙂

**Comment by ErikLitonius** [comment]
Oh, that's interesting. In that case, I can use Chrome instead as a workaround. Thank you for making this tool and for taking the time to reply!

Erik

**Comment by chekdotdev** [comment]
It looks like safari is saving the file names appropriately now (macOS 10.15, Safari 13)

**Comment by aniav** [comment]
I'll close the issue then, thank you 🌟
