### ISSUE TITLE
YNAB CSV Import Format changed

### ISSUE THREAD

**Issue by benjspriggs** [aniav/ynab-csv#12]
The format for the importing CSV has changed:
```
Date, Payee, Memo, Inflow, Outflow
```
to:
```
Date, Payee, Memo, Amount
```
as of today (11/17/18) the import CSV doesn't work for a file exported by `ynab-csv`.

**Comment by aniav** [comment]
Thank you! i will look into it ✌️

**Comment by kronn** [comment]
I heard from a friend that this is not the case for everyone. Maybe a selector for the format is needed?

**Comment by aniav** [comment]
@benjspriggs the format is exactly the same for me as it was. When you try to do an import do you actually have a different view than the one below?

<img width="687" alt="ynab2" src="https://user-images.githubusercontent.com/182546/48739964-f022fc00-ec55-11e8-9910-9a4ca9a984eb.png">

The official YNAB docs also didn't change as to the format. BTW You can choose the amount to be placed just in the Outflow column if that's the case and YNAB will gracefully consume it and process the -/+ signs into proper columns, so you should still be able to import a CSV.

Let me know if you have any more insights 🙌

**Comment by benjspriggs** [comment]
Of course, @aniav!

I recently did an export of a credit card transaction history and ran it through the tool to get the inflow and outflow categories. The exported CSV from the tool works, but there was some confusion from YNAB itself.

When using the 'Import' on an almost valid CSV from the YNAB desktop UI (on Firefox 63.0.3 64bit) I get a dialog:

![image](https://user-images.githubusercontent.com/7821629/48859453-ec38cc00-ed72-11e8-9850-979897f6369b.png)

and a `ynab_sample_import.csv` with the column headers:
```
Date, Payee, Category, Amount
```
I'm assuming this is an old sample and doesn't affect the current import/ export - if you create a CSV with this format, it works as well.

I'm going to close this since it doesn't seem like it affects the tool itself, but I'd figure I'd leave it here for future reference.

**Comment by aniav** [comment]
@benjspriggs I have added the other columns format. Would be nice if you could check it as I still have the old column format in my version of YNAB :)
