### ISSUE TITLE
YNAB CSV Import Format

### ISSUE THREAD

**Issue by lenkadv** [aniav/ynab-csv#14]
The YNAB CSV import format changed for me today. This has been reported before here https://github.com/aniav/ynab-csv/issues/12
It seemed not everybody was affected at that time (I wasn't) and the issue was closed. I now experience exactly what benjspriggs described. Maybe YNAB rolled it out gradually? I wonder what the status is now because correcting the csv headings manually is cumbersome and I'd love to use the tool directly.

**Comment by aniav** [comment]
@lenkadv is this about the web app? Can you provide a screenshot maybe?

**Comment by lenkadv** [comment]
@aniav It's exactly as benjspriggs described here: https://github.com/aniav/ynab-csv/issues/12

The format for the importing CSV has changed:

Date, Payee, Memo, Inflow, Outflow
to:

Date, Payee, Memo, Amount

The tool works fine, but YNAB doesn't accept the CSV and I get this message: 


![image](https://user-images.githubusercontent.com/46053263/50352747-7f1d7f80-0546-11e9-9ee1-eb818cd982d7.png)


I have to change the headings manually and then it works okay.

**Comment by aniav** [comment]
@lenkadv I have just added the possibility to change the column format, can you check if it works? It should also save the selected column format in localStorage so it's always the last one you used 🌟

**Comment by lenkadv** [comment]
@aniav Works perfectly! Thanks a lot!

**Comment by aniav** [comment]
![](https://media.giphy.com/media/7FgmUJQNe7ovzjAqt3/giphy.gif)
