### ISSUE TITLE
Outflow data Missing

### ISSUE THREAD

**Issue by ukmercenary** [aniav/ynab-csv#18]
When I import my banks .csv it is showing all the correct columns on your import tool. However when I import it into YNAB it leaves off the outflow.

**Comment by aniav** [comment]
Can you show a screen from YNAB of when you attempt to import? And an example file you exported from the converter (do anonimyse it before sending ;)) if that's possible. I'm not able to get to the core of the issue without more details 🙏

**Comment by ukmercenary** [comment]
Hi, thanks for the quick reply, I clicked on the toggle button to only show the 4 columns, and have imported this and now it seems to work!

**Comment by aniav** [comment]
Thanks! Glad it's fine now! 😁
