### ISSUE TITLE
utf-8 does not work or German special characters not shown correctly

### ISSUE THREAD

**Issue by zasq** [aniav/ynab-csv#19]
Hi there!
Thanks for your script, it's very helpful! In the past few weeks/months the German characters like ö ö ü ß are not shown correctly. Is there a way to fix that?
Thank you!
Best, Saskia

**Comment by aniav** [comment]
Hi, could you provide an example file? It might be that your bank file is not encoded in utf-8 if the characters are not showing and you should try with different encoding. If this still persists could you anonymise data and provide an example file so I can check what's up?

Thanks!

**Comment by vjustov** [comment]
The same thing happened to me, turns out the file is PROBABLY encoded along the lines of windows-1250

**Comment by aniav** [comment]
I'd like to help but without an example file I'm not really able to.

Also: did you try and play with the encoding button when uploading the file? My bank does exports with windows-1250 and I use it with that encoding setting 🙌

**Comment by zasq** [comment]
Hey Ania. Sorry, I forgot about this... Yes, it works when I change the
encoding setting! The bank must have changed their encoding! All the best,
Saskia

Am Sa., 30. März 2019 um 09:21 Uhr schrieb Ania Warzecha <
notifications@github.com>:
