### ISSUE TITLE
Payee, Memo, Amount are not imported

### ISSUE THREAD

**Issue by dariabun** [aniav/ynab-csv#20]
Trying to convert a bank csv fife and all the fields are empty after Loading file from the bank
![image](https://user-images.githubusercontent.com/16592490/57098542-5bcec200-6ce8-11e9-859e-c0985e5fd7b8.png)

**Comment by aniav** [comment]
@dariabun you need to pick the colums to be mapped to Payee, Memo and Amounts. In the above screen they are empty.
![pick_fields](https://user-images.githubusercontent.com/182546/57112124-f823b380-6d3e-11e9-83b7-7a95e8c261c2.jpg)

The columns will not automatically pull from the file from your bank if there are no fields matching Payee, Memo etc. So. e.g. you need to pick Amount from your file in the field Outflow and in the field Inflow, in order for the converter to "know" which data to pick for these columns.
