### ISSUE TITLE
Textarea for pasting CSV

### ISSUE THREAD

**Issue by benallfree** [aniav/ynab-csv#22]
Any thoughts on providing a textarea option for pasting CSV from a clipboard? 

Use case: My bank does not offer direct connections or transaction exports (I know, stupid). As a workaround, I use a Chrome plugin to grab my banking info from an HTML table. The plugin copies the CSV to the clipboard, then I have to paste it into a temporary file, upload to ynab-csv, then download the other format, then import that into YNAB. 

This would save a step.

**Comment by aniav** [comment]
Sounds like some pain! 🙈 To be honest I didn't plan to add anything like that, but I would accept an improvement like that if someone submitted it.

Did you maybe check if there is no better plugin, which would download a CSV file instead of forcing you to create a file?

**Comment by aniav** [comment]
Hey @benallfree I have now added the possibility to paste CSV contents. You need to click anywhere around the "Drop file" area and then paste. It should load the file. Let me know if that works properly for you, I have only tested on my files 🙌
