### ISSUE TITLE
Please make it possible to clear info in dropdown menu

### ISSUE THREAD

**Issue by Siiffloor** [aniav/ynab-csv#25]
My bank does not fill out a payee. So I need that field to be empty, but as it is now it is filled with the date from the drop down meu and I am only able to select from the other columns in the CSV file which are also not correct. I would like to be able just to clear that field and leave it empty.

Even when reloading the page and importing a new csv file, the converter now autofill that field with the column I chose the last time.

Thanks in advanece
Siif

**Comment by aniav** [comment]
Thank you for reporting @Siiffloor 🙌I agree this feature is needed, I didn't know this might be an issue.

For a temporary fix, you can clear local storage in your browser, it stores your previous mappings so you don't have to put it again.

**Comment by aniav** [comment]
This has been fixed 👍
