### ISSUE TITLE
blank column headings

### ISSUE THREAD

**Issue by mcmahonsport** [aniav/ynab-csv#27]
Is it possible to have 'Blank' as a column heading, at the moment you have to choose a heading which can fill 'memo' with useless information.
![Annotation 2020-01-21 115324](https://user-images.githubusercontent.com/43268308/72802978-dd82c900-3c44-11ea-9a35-cf7eae6befbe.jpg)

**Comment by aniav** [comment]
Thank you for the report, it should definitely be possible. I'm not sure if I will have time to work on this any time soon though 🙌

**Comment by aniav** [comment]
Or actually, I just fixed it 😛
