### ISSUE TITLE
Converted Data Reads into YNAB as No Transactions Present

### ISSUE THREAD

**Issue by vlstrode** [aniav/ynab-csv#28]
CSV File from my  bank, had date, payee, memo (all null), and amount.  This program changed the header names of my file.  When importing file to YNAB, returns no transactions present.

Oddly enough, this happens when I attmempted to read a DFX file in as well.

**Comment by aniav** [comment]
Hey @vlstrode, thank you for reporting this. Could you provide an example file with this happening so that I can check against something? I'm interested in not only values but also delimiters and if the data is in parentheses, so that I know what to fix too 🙌

**Comment by aniav** [comment]
I'm closing this because of lack of information. Feel free to reopen 🙌
