### ISSUE TITLE
negative outflow results in ynab mapping it back to inflow

### ISSUE THREAD

**Issue by chadxz** [aniav/ynab-csv#30]
my bank csv looks like this

```csv
"Account","Transaction Date","Posted Date","No.","Description","Debit","Credit"
"Family Checking * 1025","2/3/2020","2/3/2020","","MOBILE DEPOSIT-AVAIL TONIGHT","","36.0000"
"Family Checking * 1025","2/3/2020","2/3/2020","","VANGUARD BUY     INVESTMENT","-100.0000",""
"Family Checking * 1025","2/3/2020","2/3/2020","","CAPITAL ONE      MOBILE PMT","-109.6100",""
```

and when i use the tool, it maps it to this:

```csv
"Date","Payee","Memo","Outflow","Inflow"
"2/3/2020","MOBILE DEPOSIT-AVAIL TONIGHT","","","36.0000"
"2/3/2020","VANGUARD BUY     INVESTMENT","","-100.0000",""
"2/3/2020","CAPITAL ONE      MOBILE PMT","","-109.6100",""
```

But when I import this into YNAB, it treats the negative outflow as an inflow. It's an easy fix on my side... i do a find/replace for `"-` and replace it with `"`

Would be nice if the tool did the right thing here.

P.S. i use this tool pretty much every time i do budgeting, so thank you.

**Comment by aniav** [comment]
Thank you for reporting this. This should be fixed now 🙌

**Comment by aniav** [comment]
Also thank you so much for providing the test file, I have a hard time testing without the special cases people encounter 💃

**Comment by chadxz** [comment]
thanks a lot @aniav !
