### ISSUE TITLE
Memos with quote are not escaped correctly

### ISSUE THREAD

**Issue by notepid** [aniav/ynab-csv#31]
If a memo field contains a quote (") it is not escaped correctly and thus the YNAB importer fails.

Example

`21.03.2020	Varekjøp	="PAYPAL *SOMETHING"	-20.95`

is transformed to

`"21.03.2020","","="PAYPAL *SOMETHING"","","-20.95"`

Possible solutions are to either remove the quote from the text when its transformed or apply correct CSV escaping by replacing all quotes in the import text with two quotes (""). 

See https://stackoverflow.com/a/17808731

**Comment by aniav** [comment]
I fixed that now. Could you confirm if it fixed the issue for you?
