### ISSUE TITLE
Support for UTF-8

### ISSUE THREAD

**Issue by mgra8ski** [aniav/ynab-csv#33]
There is some issue with Polish characters: Ą,Ć,Ę,Ł,Ó,Ś,Ż,Ź
I think this is a problem with encoding.

**Comment by aniav** [comment]
Hey @MartinCom, did you try choosing different encoding from the Input file config before uploading the file? 

<img width="613" alt="Screenshot 2020-05-21 at 16 03 16" src="https://user-images.githubusercontent.com/182546/82566702-9a961b00-9b7c-11ea-99ea-c740955a1b40.png">

**Comment by mgra8ski** [comment]
Hey, I use UTF-8 always. When I change to Windows-1250 is working :). Thank you.

**Comment by aniav** [comment]
Yeah, well, Polish banks are stuck with encoding in the 90's 😛

**Comment by mgra8ski** [comment]
Yes, that is true :D
