### ISSUE TITLE
YNAB-CSV Converter - No valid data to import

### ISSUE THREAD

**Issue by Mapretor** [aniav/ynab-csv#35]
I've used the Ynab-CSV converter often (thanks!) 

In the last month I've come across the error message when following the process to download and converting the csv file. 

**Zero transactions to Import
We could not find any valid transactions to import from the files provide**

When I open the csv file in Apple's Numbers app, it shows a blank table. yet, I can see the data in the CSV Converter online

Please assist?

**Comment by aniav** [comment]
@Mapretor could you provide an example file that I could test on? You could change the data so that it's anonymous. I can't assist without an example file 🙌

**Comment by Mapretor** [comment]
Hi

My enquiry below refers

Please see attached an example file. The below screenshot indicates the csv file from my bank that I dropped into the CSV converter, which produced the ynab_data_xxx.csv file. This file is however empty and cannot be uploaded in YNAB

[cid:image001.png@01D68A02.6DACFEF0]

Thanks in advance
Marina

**Comment by aniav** [comment]
Hey Marina,
I think you need to supply the screenshot directly on github. Adding it as an e-mail attachment seems to not come through.

Thank you 🙂

**Comment by aniav** [comment]
I cannot help here without the screenshots attached so closing. Feel free to reopen when you can add examples 🙌
