### ISSUE TITLE
YNAB CSV Converter

### ISSUE THREAD

**Issue by rialbrown** [aniav/ynab-csv#36]
When I try to import my Numbers csv file into the YNAB csv converter, it only imports 10 lines.  This has never happened before.  I have about 50 lines to import and I need to get this done quickly so I can budget my credit card.  I cannot attach the file because this does not support csv files.

Jocelyn Brown

**Comment by aniav** [comment]
@rialbrown
Hey Jocelyn,
thank you for the report. Could you try and change the file extension from `.csv` to `.txt` and then add it here?
I'm attaching an example of such file:
[testowa_historia_.txt](https://github.com/aniav/ynab-csv/files/5295224/testowa_historia_.txt)

I will only be able to support you with input data. I'm using the tool regularly with my files and just checked them with reports from two banks and it worked properly, so the issue has to be specific to your bank. You could also tell me the bank name and I could see if they have example files on their documentation page.

Thank you 🙂

**Comment by aniav** [comment]
I need to close this one as I can't help without example data. Feel free to reopen with example data or open a new issue 🙌
