### ISSUE TITLE
YNAB Converter

### ISSUE THREAD

**Issue by lassensurf** [aniav/ynab-csv#38]
I've used this converter tool in the past without issue, it's great! But today, not all the data is importing into the tool. It's there when I open the file in excel, but it doesn't load it all in the YNAB tool. Any ideas?

**Comment by aniav** [comment]
Thank you for the report @lassensurf. I would only be able to help if you'd provide some (anonymised) file contents. Can be pasted here as raw text. Without that I'm not really able to do much.

You could also take one of the previous excels that worked for you earlier and try uploading it to the converter to see if they also get broken or is it fine for them but breaks for the current one. This might lead us to the reason too.

**Comment by lassensurf** [comment]
I figured it out, I had to delete some lines from the csv that had items in
it like "pending" then import that new csv into the converter.

Thanks!

**Comment by aniav** [comment]
Happy it worked! Were these lines containing only the word pending so that the converter was cutting off everything below of them?

**Comment by lassensurf** [comment]
It was only importing the dates along with the words "Pending" or "Cleared"
and nothing else. I don't think it could recognize the column headers that
said "Date" "Amount" "Description" etc.Once I got rid of some of the other
lines, it all worked fine.
