### ISSUE TITLE
Feature Request - remove Charles Schwab headers

### ISSUE THREAD

**Issue by eliotlandrum** [aniav/ynab-csv#39]
Since Charles Schwab and Plaid are having a little squabble and YNAB can't currently connect to Schwab, I have been using this tool to keep my checking account transactions updated. However, they put these annoying headers above the transactions:

> Transactions  for Checking account Checking XXXXXX-123123 as of 02/22/2021 13:30:55 ET From 02/01/2021 to 02/22/2021
> "Date","Type","Check #","Description","Withdrawal (-)","Deposit (+)","RunningBalance"
> "Pending Transactions are not reflected within this sort criterion."
> "Posted Transactions"

To use this tool, I have to remove the first, third, and fourth lines to get it to work. Would be really cool if it could take care of that for me.

**Comment by aniav** [comment]
I am happy to accept a change that would allow someone to remove specific lines from the import 🙌 For now I can't guarantee I would have time to work on this any time soon.

**Comment by aniav** [comment]
Since [Charles Schwab is now supported natively in YNAB](https://www.reddit.com/r/ynab/comments/176675d/charles_schwab_work_with_ynab/) I will close this issue 🙌
