### ISSUE TITLE
Export is blank. 

### ISSUE THREAD

**Issue by mcdrop** [aniav/ynab-csv#40]
Hello. 
<img width="927" alt="Screen Shot 2021-06-11 at 7 42 49 AM" src="https://user-images.githubusercontent.com/85751725/121704851-fc2b6f00-ca88-11eb-9b9f-97ace7a5ffcc.png">
[ynab_data_20210611 (1).csv](https://github.com/aniav/ynab-csv/files/6639261/ynab_data_20210611.1.csv)

Import shows data, but export is blank. 

Thanks for helping me with this. 

~Marissa

**Comment by aniav** [comment]
Hey Marissa, I would be able to help if you provided the original export from the bank. Without it I can't see what's wring. If you could anonimise the original fiel and attach it here, this would be great. Thank you 👌

**Comment by aniav** [comment]
I have to close this issue as I cannot help without an example file 🙌  Feel free to reopoen when you can add example data.
