### ISSUE TITLE
Unicode characters

### ISSUE THREAD

**Issue by ipxwork** [aniav/ynab-csv#45]
The CSV file contains columns with unicode characters, Danish alphabet in my case

![image](https://user-images.githubusercontent.com/7421416/137623518-c22af148-ddf0-41e2-b4cb-ec3459da0ab4.png)

**Comment by aniav** [comment]
Hey @ipxwork you need to check what is the encoding of the file you are uploading and you need to choose it from the list. Like in the recording below. For Danish my best bet would be: ISO-8859-4. You need to choose it before adding the file and then it should show up properly.

Let me know if that worked! :)


https://user-images.githubusercontent.com/182546/137631532-fd64aed0-4a48-4661-ad9c-9bf5c8b308b8.mov

**Comment by ipxwork** [comment]
Thanks @aniav, it works ;)
Was silly from my side not to check before complaining :P
