### ISSUE TITLE
impossible to use the plateform

### ISSUE THREAD

**Issue by Juliendrinkscoffee** [aniav/ynab-csv#46]
Good morning,

I am sorry but I can t use your plateform with all the csv form I would like to convert
I have tried different files, from different banks but the converter doesnot seems to work anymore

Maybe you could check ?
Many thanks

Julien

**Comment by aniav** [comment]
Could you explain what you mean by "doesnt seem to work anymore"?

**Comment by Juliendrinkscoffee** [comment]
sure sorry
please find some print screen in attachment
the original csv files are coming from different banks like Hypoverein in Germany or N26
thanks again for your help
![Opera Snapshot_2021-10-18_125825_aniav github io](https://user-images.githubusercontent.com/92711673/137718737-9c6d1b49-5394-4415-97aa-537f8472d34e.png)
![Opera Snapshot_2021-10-18_125608_aniav github io](https://user-images.githubusercontent.com/92711673/137718739-53e20c09-0148-4d21-a8a5-21e0c3d2feb2.png)
![Opera Snapshot_2021-10-18_125945_aniav github io](https://user-images.githubusercontent.com/92711673/137718742-2cd3e591-1c83-4a6c-b781-d69b3b8bf440.png)
![Opera Snapshot_2021-10-18_125902_aniav github io](https://user-images.githubusercontent.com/92711673/137718743-3702b692-50fc-4f25-ac70-9f4447903966.png)
![Opera Snapshot_2021-10-18_125945_aniav github io](https://user-images.githubusercontent.com/92711673/137718776-687f5ddc-4949-4903-83c2-0e5e1e1b672e.png)
![Opera Snapshot_2021-10-18_125902_aniav github io](https://user-images.githubusercontent.com/92711673/137718778-a9681a3a-1299-4caf-baa8-6979945e7370.png)
![Opera Snapshot_2021-10-18_125825_aniav github io](https://user-images.githubusercontent.com/92711673/137718779-82bd7a77-cf47-433d-92fc-44e8a45164b3.png)
![Opera Snapshot_2021-10-18_125608_aniav github io](https://user-images.githubusercontent.com/92711673/137718781-79c52029-e0b7-4cea-b9ef-eb89aa8d3fd7.png)


julien

**Comment by Juliendrinkscoffee** [comment]
I am using Opera browser and Win 10

**Comment by aniav** [comment]
Thank you, could you also show me what you have in the Input file config (like in the screenshot below)? It does look like on your end it's not parsing the file properly.

<img width="870" alt="Screenshot 2021-10-18 at 16 22 25" src="https://user-images.githubusercontent.com/182546/137749990-9433e2b2-bc33-4ac3-b746-a23cc7b8bdd6.png">

**Comment by Juliendrinkscoffee** [comment]
![Opera Snapshot_2021-10-18_162741_aniav github io](https://user-images.githubusercontent.com/92711673/137751085-b9e1b271-a4da-4a3b-95e0-f7646fe069de.png)

**Comment by aniav** [comment]
Hmm, this looks properly. You could play with the "Celle delimiter" setting and try to force `,` and see if it helps. I'd also try a different browser, I never did any tests on Opera, so I am not even sure if it's working properly there. Might be that some kind of update to the browser changed how the tool is acting.

**Comment by Juliendrinkscoffee** [comment]
it seems that the character encoding is different
What do you think I should use then ?

**Comment by Juliendrinkscoffee** [comment]
ok , what browser you think would work better ?

**Comment by aniav** [comment]
I was testing with Firefox and Chrome.

As for character encoding if you don't see any weird characters after the file is loaded you don't need to change from UTF-8. If you see weird characters you could try ISO-8859-15 (which is common for German).

**Comment by Juliendrinkscoffee** [comment]
I have to tell you that I have some good results with this configuration in attachment
thanks again for your help and your time
have a nice day
Juli
![YNAB CSV Convert](https://user-images.githubusercontent.com/92711673/137852026-dd0c0302-052c-4027-939d-32dd23d73a4f.png)
en

**Comment by aniav** [comment]
Great, glad this works ;)
