### ISSUE TITLE
Cant download the file 

### ISSUE THREAD

**Issue by Todo328** [aniav/ynab-csv#51]
Hey, 

Did write to support, did use different browsers still not able to download the file .

Screenshot attached

best regards 
Tomas
![converter](https://user-images.githubusercontent.com/128596421/226888513-c04d2b25-e40c-4a24-a156-f6ec73d5d285.JPG)

**Comment by aniav** [comment]
Hey Tomas,
the screenshot you attached is from a different website. The version I am maintaining and the one that you have created an issue for is available under:
https://aniav.github.io/ynab-csv/

You should upload a bank statement from your bank to be able to move forward and download the file needed for YNAB.

Please try that and let me know if that helped, thank you!

**Comment by Todo328** [comment]
It did work.

Thank you very much

best regards
Tomas

st 22. 3. 2023 o 18:48 Ania Warzecha ***@***.***> napísal(a):
