### ISSUE TITLE
Empty CSV YNAB file

### ISSUE THREAD

**Issue by jorgesufo** [aniav/ynab-csv#54]
The YNAB sheet export is empty, although the imported CSV is not.

**Comment by aniav** [comment]
Hey @jorgesufo, are you able to provide an example CSV with anonymised personal details so I could see what could be the problem? Without an example file I am not able to help or check what's wrong.

**Comment by jorgesufo** [comment]
Hi aniav, here's the original csv anonymized:
[anon bank export csv.csv](https://github.com/aniav/ynab-csv/files/11838111/anon.bank.export.csv.csv)

Here's the YNAB export:
[ynab_data_20230622 (1).csv](https://github.com/aniav/ynab-csv/files/11838123/ynab_data_20230622.1.csv)

Thanks!

**Comment by aniav** [comment]
Thank you for the details!

I just checked the file and it worked just fine. I dropped a recording of how I used the file. Can you check if you are choosing the data to be used for the export the way I did?

https://github.com/aniav/ynab-csv/assets/182546/4649b424-ffeb-44e4-a210-28e0a13f0f09

**Comment by aniav** [comment]
I'll close this issue for now. Feel free to reopen with more details 🙌
