### ISSUE TITLE
feature to inverse the amount column?

### ISSUE THREAD

**Issue by dlethin** [aniav/ynab-csv#59]
This is a really good tool. I cam across it when I was running into some problems currently being investigated where my discover card it not auto downloading transactions so I was trying this manual method

I ran into an issue where the CSV files discover card supplies mark outgoing amounts with a positive dollar amount and incoming amounts with a negative amount.  Would be nice to have a flag as an option to inverse these values?

thanks for sharing this tool

**Comment by aniav** [comment]
Thank you for all the information. I think the tool already has what you need. Does the following video solve your case?


https://github.com/aniav/ynab-csv/assets/182546/320224a6-0e1d-48a3-bb34-d06774fa1592

**Comment by aniav** [comment]
I'll close this for now. Feel free to reopen if you still have the problem 🙌
