### ISSUE TITLE
Imports for CSV's where the transactions start at row 1

### ISSUE THREAD

**Issue by danjustice2** [aniav/ynab-csv#61]
Hi,

My bank's CSV's don't have any kind of indicator at row 1 of what each of the rows are, so every time I want to use the converter, I have to manually add an extra row to the top in order to not skip the first transaction. Some sort of solution to this would be much appreciated!

Here is an example of one of my CSV's.

```
09-11-2023;"Fakta";-326,03
07-11-2023;"Just Eat.dk 6DJ524\Lyngbyvej 20, 2.\Copenhagen\ ";-143,00
07-11-2023;"PAYPAL *GOOGLE GOOGLE, 35314369001 ";-17,00
06-11-2023;IDA INGENIØRFORE. I DANMARK;-289,25
```

Best,
Dan

**Comment by aniav** [comment]
Hey @danjustice2, thank you for the report. It's actually already been reported in #47. So I'll close this issue as duplicate. I'd welcome any contribution that would fix the issue as I'm very limited in time to maintain this tool 🙌
