### ISSUE TITLE
First line is stripped

### ISSUE THREAD

**Issue by michdorf** [aniav/ynab-csv#63]
My bank doesn't include column headers in the exported csv file. It would be appreciated to be able to include the first line in the export. At the moment it ends up beeing treated as a header-line and not imported into YNAB.

**Comment by aniav** [comment]
Thank you for the report 🙇‍♀️ You can already do it by using the fill header with the first row. It will duplicate the first row basically.
<img width="711" alt="Screenshot 2023-11-16 at 14 24 36" src="https://github.com/aniav/ynab-csv/assets/182546/abdc3d9f-b7c1-468b-9da7-db79afc692a2">
