### ISSUE TITLE
Issue with Starling Bank

### ISSUE THREAD

**Issue by simon-wildings-studio** [aniav/ynab-csv#64]
Converter seems to have stopped working for CSV file from Starling Bank. Throwing up the 'Zero Transactions To Import' error. Any advice?

**Comment by aniav** [comment]
@simon-wildings-studio thank you for the info. Could you maybe send an example anonymised file so I could try it and fix it? Thank you!

**Comment by simon-wildings-studio** [comment]
Hi Ania,

I've had another look at this and the output file from the converter was
empty apart from the headings.

I've attached an anonymised file for you to test.

Both attached.

**Comment by simon-wildings-studio** [comment]
[StarlingStatement_2023-11 (11).csv](https://github.com/aniav/ynab-csv/files/13657366/StarlingStatement_2023-11.11.csv)

Realised this didn't get attached when I replied by e-mail...

**Comment by aniav** [comment]
Hey @simon-wildings-studio I tried the file you provided and it works well. Can you double check if you are doing all the steps like I did? Feel free to reopen the issue if the problem is still there.

https://github.com/aniav/ynab-csv/assets/182546/a72f4dde-ed0a-44ed-b401-0839a7f22145
