### ISSUE TITLE
MMM-DD-YYYY Not an available format when importing into YNAB

### ISSUE THREAD

**Issue by mthibode13** [aniav/ynab-csv#73]
Importing activity that comes from a MMM-DD-YYYY format; however, the converter leaves it in that format. The problem is that YNAB app does not recognize that format when importing. All of its month first options are MM.

**Comment by aniav** [comment]
Hey @mthibode13, thank you for the report. There already is an issue to format the date #10. I'll close this issue and add your details and the specific date that's not being processed to the one that's already open to keep things in one place. Thank you!
