### ISSUE TITLE
Number formating in different countries

### ISSUE THREAD

**Issue by TheShirtDude** [aniav/ynab-csv#75]
Hi, I live in Norway and with a few other counties we use , as the decimal seperator not the .
I would be sweet to see a setting for the in and out cloumn to specify this, and get it fixed as part of the conversion.
Other than that the converter looks great, thanks!

**Comment by aniav** [comment]
Hey @TheShirtDude there is a setting inside the budget settings in YNAB that lets you decide what's the import format. That's the way to adjust to the import file. Let me know if this helped!

**Comment by TheShirtDude** [comment]
Nice - thanks a lot!Mvh/ Best regards/ 此致Roger Fløttum/ 福罗杰Mobil: +47 9011 228223. juli 2024 kl. 06:14 skrev Ania Warzecha ***@***.***>:﻿
Hey @TheShirtDude there is a setting inside the budget settings in YNAB that lets you decide what's the import format. That's the way to adjust to the import file. Let me know if this helped!
