### ISSUE TITLE
Deutsche Kreditbank (DKB) new banking CSV format brakes the converter

### ISSUE THREAD

**Issue by ernst23** [aniav/ynab-csv#76]
Hi,

my bank did update their online banking portal and while doing that they did something bad to the CSV format, so now your converter sadly doesn't work on the generated files. 

I contacted them some time ago asking them to fix their CSV to a proper format, but the don't seem to care. Can you please help? 😥

This is an example export CSV from DKB (Deutsche Kreditbank): 
https://gist.github.com/ernst23/b6bc4bd5ccaca77ab1ee7f3c1459baad

The converter gets the column headings wrong, which are in row 5. 

Thank you!
ernst23

**Comment by aniav** [comment]
Hey @ernst23 I managed to get that file to work with the following setup:
<img width="844" alt="Screenshot 2024-09-09 at 21 41 19" src="https://github.com/user-attachments/assets/682bc262-2708-4724-9568-6a5b37e71bd2">

You basically need to tell the converter to start from the line where the headers are. And this gave me the options to choose proper values.
<img width="1202" alt="Screenshot 2024-09-09 at 21 42 31" src="https://github.com/user-attachments/assets/15f5a3cf-9307-4d86-874b-22c44718a21d">

Let me know if it worked! 👋

**Comment by ernst23** [comment]
> Let me know if it worked! 👋

Thank you very much @aniav! It works! (Besides the bank did change the format again from ; to , so it didn't work in the first attempt, but now it does.)

You saved me a lot of time in YNAB - big internet stranger thanks to you. :)

**Comment by aniav** [comment]
I'm happy it helps! ✨
