### ISSUE TITLE
Convert csv to qfx?

### ISSUE THREAD

**Issue by pdvachon** [aniav/ynab-csv#8]
I am sorry, my previous post was in error. However, have you considered modifying your excellent utility to convert csv to qfx?

**Comment by aniav** [comment]
Hey @pdvachon I didn't consider modifying the utility to produce qfx. I didn't know this would be a needed use case. Why do you think it would be useful?

**Comment by pdvachon** [comment]
Hi Ania,

Now that I've used your utility several times, I no longer see the need for qfx, which are Quicken files. I was under the impression they were more compatible with YNAB. However, csv files seem to work flawlessly. Thank you for creating this utility. My credit card company recently switched banks and the new bank only exports to csv.

Kind regards,
Peter

On Aug 21, 2018, at 03:48 PM, Ania Warzecha <notifications@github.com> wrote:

Hey @pdvachon I didn't consider modifying the utility to produce qfx. I didn't know this would be a needed use case. Why do you think it would be useful?

**Comment by aniav** [comment]
@pdvachon thanks! I hope your bank doesn't break the file in the future 💃
