### ISSUE TITLE
Default name for unnamed columns

### ISSUE THREAD

**Issue by rjaneczko** [aniav/ynab-csv#9]
When loading CSV with empty names for some columns the app always choose the last empty-name column when selecting one of the empty names in selector. I.e. when column 3, 4 and 5 has empty name, and user selects 4 column, it receives data from column 5 not 4.

It would be fine to use default name for columns with empty names, i.e. column-3, column4 etc.

**Comment by aniav** [comment]
Makes sense! I'd be happy to accept a pull request with changes for this scenario, as I don't expect to have time to fix this at least ~4 weeks 🙌

**Comment by aniav** [comment]
This is now fixed ✨👋
